USE [Jackpot]
GO

EXEC dbo.sp_rename @objname = N'[dbo].[RaceHorse]', @newname = N'RaceHorse_old', @objtype = N'OBJECT'
GO

USE [Jackpot]
GO

SET ANSI_NULLS ON
GO

CREATE TABLE [dbo].[RaceHorse]
(
	[RecordSpec] [nchar](2) COLLATE Japanese_CI_AS NULL,
	[DataKubun] [nchar](1) COLLATE Japanese_CI_AS NULL,
	[MakeDate] [date] NULL,
	[RaceDate] [date] NULL,
	[JyoCd] [nchar](2) COLLATE Japanese_CI_AS NULL,
	[Kaiji] [int] NULL,
	[Nichiji] [int] NULL,
	[RaceNum] [int] NULL,
	[RaceId] [nchar](20) COLLATE Japanese_CI_AS NOT NULL,
	[KettoNum] [nchar](10) COLLATE Japanese_CI_AS NOT NULL,
	[Wakuban] [int] NULL,
	[Umaban] [int] NULL,
	[Bamei] [nvarchar](36) COLLATE Japanese_CI_AS NULL,
	[UmaKigoCd] [nchar](2) COLLATE Japanese_CI_AS NULL,
	[SexCd] [nchar](1) COLLATE Japanese_CI_AS NULL,
	[HinsyuCd] [nchar](1) COLLATE Japanese_CI_AS NULL,
	[KeiroCd] [nchar](2) COLLATE Japanese_CI_AS NULL,
	[Barei] [float](53) NULL,
	[TozaiCd] [nchar](1) COLLATE Japanese_CI_AS NULL,
	[ChokyosiCode] [nchar](5) COLLATE Japanese_CI_AS NULL,
	[ChokyosiRyakusyo] [nvarchar](8) COLLATE Japanese_CI_AS NULL,
	[BanusiCode] [nchar](6) COLLATE Japanese_CI_AS NULL,
	[BanusiName] [nvarchar](64) COLLATE Japanese_CI_AS NULL,
	[FukusyokuCd] [nvarchar](60) COLLATE Japanese_CI_AS NULL,
	[reserved1] [nvarchar](60) COLLATE Japanese_CI_AS NULL,
	[Futan] [float](53) NULL,
	[FutanBefore] [float](53) NULL,
	[Blinker] [nchar](1) COLLATE Japanese_CI_AS NULL,
	[IsBlinker] [bit] NULL,
	[reserved2] [nchar](1) COLLATE Japanese_CI_AS NULL,
	[KisyuCode] [nchar](5) COLLATE Japanese_CI_AS NULL,
	[KisyuCodeBefore] [nchar](5) COLLATE Japanese_CI_AS NULL,
	[KisyuRyakusyo] [nvarchar](8) COLLATE Japanese_CI_AS NULL,
	[KisyuRyakusyoBefore] [nvarchar](8) COLLATE Japanese_CI_AS NULL,
	[MinaraiCd] [nchar](1) COLLATE Japanese_CI_AS NULL,
	[MinaraiCdBefore] [nchar](1) COLLATE Japanese_CI_AS NULL,
	[BaTaijyu] [float](53) NULL,
	[ZogenFugo] [nchar](1) COLLATE Japanese_CI_AS NULL,
	[ZogenSa] [float](53) NULL,
	[IjyoCd] [nchar](1) COLLATE Japanese_CI_AS NULL,
	[NyusenJyuni] [float](53) NULL,
	[KakuteiJyuni] [float](53) NULL,
	[DochakuKubun] [nchar](1) COLLATE Japanese_CI_AS NULL,
	[DochakuTosu] [float](53) NULL,
	[Time] [float](53) NULL,
	[ChakusaCd] [nchar](3) COLLATE Japanese_CI_AS NULL,
	[ChakusaCdP] [nchar](3) COLLATE Japanese_CI_AS NULL,
	[ChakusaCdPp] [nchar](3) COLLATE Japanese_CI_AS NULL,
	[Jyuni1c] [float](53) NULL,
	[Jyuni2c] [float](53) NULL,
	[Jyuni3c] [float](53) NULL,
	[Jyuni4c] [float](53) NULL,
	[Odds] [float](53) NULL,
	[Ninki] [float](53) NULL,
	[Honsyokin] [float](53) NULL,
	[Fukasyokin] [float](53) NULL,
	[reserved3] [nchar](3) COLLATE Japanese_CI_AS NULL,
	[reserved4] [nchar](3) COLLATE Japanese_CI_AS NULL,
	[L4] [float](53) NULL,
	[L3] [float](53) NULL,
	[KettoNum1] [nchar](10) COLLATE Japanese_CI_AS NULL,
	[Bamei1] [nvarchar](36) COLLATE Japanese_CI_AS NULL,
	[KettoNum2] [nchar](10) COLLATE Japanese_CI_AS NULL,
	[Bamei2] [nvarchar](36) COLLATE Japanese_CI_AS NULL,
	[KettoNum3] [nchar](10) COLLATE Japanese_CI_AS NULL,
	[Bamei3] [nvarchar](36) COLLATE Japanese_CI_AS NULL,
	[TimeDiff] [float](53) NULL,
	[RecordUpKubun] [nchar](1) COLLATE Japanese_CI_AS NULL,
	[DmKubun] [nchar](1) COLLATE Japanese_CI_AS NULL,
	[DmTime] [float](53) NULL,
	[DmGosaP] [float](53) NULL,
	[DmGosaM] [float](53) NULL,
	[DmJyuni] [float](53) NULL,
	[Kyakusitu] [nchar](1) COLLATE Japanese_CI_AS NULL,
	[TS] [datetime2](7) NULL,
	[IsNormalRaceHorse] [bit] NULL,
	[IsValidRaceHorse] [bit] NULL,
	[FutanPercent] [float](53) NULL,
	[LifeTime] [float](53) NULL,
	[ZogenPercent] [float](53) NULL,
	[L4Avg] [float](53) NULL,
	[L3Avg] [float](53) NULL,
	[TS2] [datetime2](7) NULL,
	[RunCount] [float](53) NULL,
	[HitCountA] [float](53) NULL,
	[HitCount2] [float](53) NULL,
	[HitCount3] [float](53) NULL,
	[HitCount4] [float](53) NULL,
	[HitCount5] [float](53) NULL,
	[HitCount6] [float](53) NULL,
	[HitCountB] [float](53) NULL,
	[HitCountC] [float](53) NULL,
	[HitCountD] [float](53) NULL,
	[IsHitA] [bit] NULL,
	[IsHitB] [bit] NULL,
	[IsHitC] [bit] NULL,
	[IsHitD] [bit] NULL,
	[zTimeByRace] [float](53) NULL,
	[zTimeByRaceDev] [float](53) NULL,
	[zTimeDiffByGlobal] [float](53) NULL,
	[zTimeByGlobal] [float](53) NULL,
	[zTimeByGlobalDev] [float](53) NULL,
	[TS3] [datetime2](7) NULL,
	[IsDefault_zBarei] [bit] NULL,
	[zBarei] [float](53) NULL,
	[IsDefault_zBaTaijyu] [bit] NULL,
	[zBaTaijyu] [float](53) NULL,
	[IsDefault_zFutan] [bit] NULL,
	[zFutan] [float](53) NULL,
	[IsDefault_zFutanPercent] [bit] NULL,
	[zFutanPercent] [float](53) NULL,
	[IsDefault_zLifeTime] [bit] NULL,
	[zLifeTime] [float](53) NULL,
	[IsDefault_zNinki] [bit] NULL,
	[zNinki] [float](53) NULL,
	[IsDefault_zUmaban] [bit] NULL,
	[zUmaban] [float](53) NULL,
	[IsDefault_zZogenPercent] [bit] NULL,
	[zZogenPercent] [float](53) NULL,
	[IsDefault_zZogenSa] [bit] NULL,
	[zZogenSa] [float](53) NULL,
	[TS4] [datetime2](7) NULL,
	[IsDefault_zBareiByRace] [bit] NULL,
	[zBareiByRace] [float](53) NULL,
	[IsDefault_zBaTaijyuByRace] [bit] NULL,
	[zBaTaijyuByRace] [float](53) NULL,
	[IsDefault_zFutanByRace] [bit] NULL,
	[zFutanByRace] [float](53) NULL,
	[IsDefault_zFutanPercentByRace] [bit] NULL,
	[zFutanPercentByRace] [float](53) NULL,
	[IsDefault_zLifeTimeByRace] [bit] NULL,
	[zLifeTimeByRace] [float](53) NULL,
	[IsDefault_zNinkiByRace] [bit] NULL,
	[zNinkiByRace] [float](53) NULL,
	[IsDefault_zUmabanByRace] [bit] NULL,
	[zUmabanByRace] [float](53) NULL,
	[IsDefault_zZogenPercentByRace] [bit] NULL,
	[zZogenPercentByRace] [float](53) NULL,
	[IsDefault_zZogenSaByRace] [bit] NULL,
	[zZogenSaByRace] [float](53) NULL,
	[TS5] [datetime2](7) NULL,
	[Training_zH4_Count] [float](53) NULL,
	[Training_zH3_Count] [float](53) NULL,
	[Training_zH2_Count] [float](53) NULL,
	[Training_zL4_Count] [float](53) NULL,
	[Training_zL3_Count] [float](53) NULL,
	[Training_zL2_Count] [float](53) NULL,
	[Training_zL1_Count] [float](53) NULL,
	[IsDefault_Training_zH4_Avg] [bit] NULL,
	[Training_zH4_Avg] [float](53) NULL,
	[IsDefault_Training_zH3_Avg] [bit] NULL,
	[Training_zH3_Avg] [float](53) NULL,
	[IsDefault_Training_zH2_Avg] [bit] NULL,
	[Training_zH2_Avg] [float](53) NULL,
	[IsDefault_Training_zL4_Avg] [bit] NULL,
	[Training_zL4_Avg] [float](53) NULL,
	[IsDefault_Training_zL3_Avg] [bit] NULL,
	[Training_zL3_Avg] [float](53) NULL,
	[IsDefault_Training_zL2_Avg] [bit] NULL,
	[Training_zL2_Avg] [float](53) NULL,
	[IsDefault_Training_zL1_Avg] [bit] NULL,
	[Training_zL1_Avg] [float](53) NULL,
	[IsDefault_Training_zH4_Max] [bit] NULL,
	[Training_zH4_Max] [float](53) NULL,
	[IsDefault_Training_zH3_Max] [bit] NULL,
	[Training_zH3_Max] [float](53) NULL,
	[IsDefault_Training_zH2_Max] [bit] NULL,
	[Training_zH2_Max] [float](53) NULL,
	[IsDefault_Training_zL4_Max] [bit] NULL,
	[Training_zL4_Max] [float](53) NULL,
	[IsDefault_Training_zL3_Max] [bit] NULL,
	[Training_zL3_Max] [float](53) NULL,
	[IsDefault_Training_zL2_Max] [bit] NULL,
	[Training_zL2_Max] [float](53) NULL,
	[IsDefault_Training_zL1_Max] [bit] NULL,
	[Training_zL1_Max] [float](53) NULL,
	[TS6] [datetime2](7) NULL,
	[GUID] [uniqueidentifier] NULL,

 CONSTRAINT [RaceHorse_éÂÉLÅ[]  PRIMARY KEY NONCLUSTERED HASH 
(
	[RaceId],
	[KettoNum]
)WITH ( BUCKET_COUNT = 4194304)
)WITH ( MEMORY_OPTIMIZED = ON , DURABILITY = SCHEMA_AND_DATA )

GO

INSERT INTO [Jackpot].[dbo].[RaceHorse] ([RecordSpec], [DataKubun], [MakeDate], [RaceDate], [JyoCd], [Kaiji], [Nichiji], [RaceNum], [RaceId], [KettoNum], [Wakuban], [Umaban], [Bamei], [UmaKigoCd], [SexCd], [HinsyuCd], [KeiroCd], [Barei], [TozaiCd], [ChokyosiCode], [ChokyosiRyakusyo], [BanusiCode], [BanusiName], [FukusyokuCd], [reserved1], [Futan], [FutanBefore], [Blinker], [IsBlinker], [reserved2], [KisyuCode], [KisyuCodeBefore], [KisyuRyakusyo], [KisyuRyakusyoBefore], [MinaraiCd], [MinaraiCdBefore], [BaTaijyu], [ZogenFugo], [ZogenSa], [IjyoCd], [NyusenJyuni], [KakuteiJyuni], [DochakuKubun], [DochakuTosu], [Time], [ChakusaCd], [ChakusaCdP], [ChakusaCdPp], [Jyuni1c], [Jyuni2c], [Jyuni3c], [Jyuni4c], [Odds], [Ninki], [Honsyokin], [Fukasyokin], [reserved3], [reserved4], [L4], [L3], [KettoNum1], [Bamei1], [KettoNum2], [Bamei2], [KettoNum3], [Bamei3], [TimeDiff], [RecordUpKubun], [DmKubun], [DmTime], [DmGosaP], [DmGosaM], [DmJyuni], [Kyakusitu], [TS], [IsNormalRaceHorse], [IsValidRaceHorse], [FutanPercent], [LifeTime], [ZogenPercent], [L4Avg], [L3Avg], [TS2], [RunCount], [HitCountA], [HitCount2], [HitCount3], [HitCount4], [HitCount5], [HitCount6], [HitCountB], [HitCountC], [HitCountD], [IsHitA], [IsHitB], [IsHitC], [IsHitD], [zTimeByRace], [zTimeByRaceDev], [zTimeDiffByGlobal], [zTimeByGlobal], [zTimeByGlobalDev], [TS3], [IsDefault_zBarei], [zBarei], [IsDefault_zBaTaijyu], [zBaTaijyu], [IsDefault_zFutan], [zFutan], [IsDefault_zFutanPercent], [zFutanPercent], [IsDefault_zLifeTime], [zLifeTime], [IsDefault_zNinki], [zNinki], [IsDefault_zUmaban], [zUmaban], [IsDefault_zZogenPercent], [zZogenPercent], [IsDefault_zZogenSa], [zZogenSa], [TS4], [IsDefault_zBareiByRace], [zBareiByRace], [IsDefault_zBaTaijyuByRace], [zBaTaijyuByRace], [IsDefault_zFutanByRace], [zFutanByRace], [IsDefault_zFutanPercentByRace], [zFutanPercentByRace], [IsDefault_zLifeTimeByRace], [zLifeTimeByRace], [IsDefault_zNinkiByRace], [zNinkiByRace], [IsDefault_zUmabanByRace], [zUmabanByRace], [IsDefault_zZogenPercentByRace], [zZogenPercentByRace], [IsDefault_zZogenSaByRace], [zZogenSaByRace], [TS5], [Training_zH4_Count], [Training_zH3_Count], [Training_zH2_Count], [Training_zL4_Count], [Training_zL3_Count], [Training_zL2_Count], [Training_zL1_Count], [IsDefault_Training_zH4_Avg], [Training_zH4_Avg], [IsDefault_Training_zH3_Avg], [Training_zH3_Avg], [IsDefault_Training_zH2_Avg], [Training_zH2_Avg], [IsDefault_Training_zL4_Avg], [Training_zL4_Avg], [IsDefault_Training_zL3_Avg], [Training_zL3_Avg], [IsDefault_Training_zL2_Avg], [Training_zL2_Avg], [IsDefault_Training_zL1_Avg], [Training_zL1_Avg], [IsDefault_Training_zH4_Max], [Training_zH4_Max], [IsDefault_Training_zH3_Max], [Training_zH3_Max], [IsDefault_Training_zH2_Max], [Training_zH2_Max], [IsDefault_Training_zL4_Max], [Training_zL4_Max], [IsDefault_Training_zL3_Max], [Training_zL3_Max], [IsDefault_Training_zL2_Max], [Training_zL2_Max], [IsDefault_Training_zL1_Max], [Training_zL1_Max], [TS6], [GUID]) SELECT [RecordSpec], [DataKubun], [MakeDate], [RaceDate], [JyoCd], [Kaiji], [Nichiji], [RaceNum], [RaceId], [KettoNum], [Wakuban], [Umaban], [Bamei], [UmaKigoCd], [SexCd], [HinsyuCd], [KeiroCd], [Barei], [TozaiCd], [ChokyosiCode], [ChokyosiRyakusyo], [BanusiCode], [BanusiName], [FukusyokuCd], [reserved1], [Futan], [FutanBefore], [Blinker], [IsBlinker], [reserved2], [KisyuCode], [KisyuCodeBefore], [KisyuRyakusyo], [KisyuRyakusyoBefore], [MinaraiCd], [MinaraiCdBefore], [BaTaijyu], [ZogenFugo], [ZogenSa], [IjyoCd], [NyusenJyuni], [KakuteiJyuni], [DochakuKubun], [DochakuTosu], [Time], [ChakusaCd], [ChakusaCdP], [ChakusaCdPp], [Jyuni1c], [Jyuni2c], [Jyuni3c], [Jyuni4c], [Odds], [Ninki], [Honsyokin], [Fukasyokin], [reserved3], [reserved4], [L4], [L3], [KettoNum1], [Bamei1], [KettoNum2], [Bamei2], [KettoNum3], [Bamei3], [TimeDiff], [RecordUpKubun], [DmKubun], [DmTime], [DmGosaP], [DmGosaM], [DmJyuni], [Kyakusitu], [TS], [IsNormalRaceHorse], [IsValidRaceHorse], [FutanPercent], [LifeTime], [ZogenPercent], [L4Avg], [L3Avg], [TS2], [RunCount], [HitCountA], [HitCount2], [HitCount3], [HitCount4], [HitCount5], [HitCount6], [HitCountB], [HitCountC], [HitCountD], [IsHitA], [IsHitB], [IsHitC], [IsHitD], [zTimeByRace], [zTimeByRaceDev], [zTimeDiffByGlobal], [zTimeByGlobal], [zTimeByGlobalDev], [TS3], [IsDefault_zBarei], [zBarei], [IsDefault_zBaTaijyu], [zBaTaijyu], [IsDefault_zFutan], [zFutan], [IsDefault_zFutanPercent], [zFutanPercent], [IsDefault_zLifeTime], [zLifeTime], [IsDefault_zNinki], [zNinki], [IsDefault_zUmaban], [zUmaban], [IsDefault_zZogenPercent], [zZogenPercent], [IsDefault_zZogenSa], [zZogenSa], [TS4], [IsDefault_zBareiByRace], [zBareiByRace], [IsDefault_zBaTaijyuByRace], [zBaTaijyuByRace], [IsDefault_zFutanByRace], [zFutanByRace], [IsDefault_zFutanPercentByRace], [zFutanPercentByRace], [IsDefault_zLifeTimeByRace], [zLifeTimeByRace], [IsDefault_zNinkiByRace], [zNinkiByRace], [IsDefault_zUmabanByRace], [zUmabanByRace], [IsDefault_zZogenPercentByRace], [zZogenPercentByRace], [IsDefault_zZogenSaByRace], [zZogenSaByRace], [TS5], [Training_zH4_Count], [Training_zH3_Count], [Training_zH2_Count], [Training_zL4_Count], [Training_zL3_Count], [Training_zL2_Count], [Training_zL1_Count], [IsDefault_Training_zH4_Avg], [Training_zH4_Avg], [IsDefault_Training_zH3_Avg], [Training_zH3_Avg], [IsDefault_Training_zH2_Avg], [Training_zH2_Avg], [IsDefault_Training_zL4_Avg], [Training_zL4_Avg], [IsDefault_Training_zL3_Avg], [Training_zL3_Avg], [IsDefault_Training_zL2_Avg], [Training_zL2_Avg], [IsDefault_Training_zL1_Avg], [Training_zL1_Avg], [IsDefault_Training_zH4_Max], [Training_zH4_Max], [IsDefault_Training_zH3_Max], [Training_zH3_Max], [IsDefault_Training_zH2_Max], [Training_zH2_Max], [IsDefault_Training_zL4_Max], [Training_zL4_Max], [IsDefault_Training_zL3_Max], [Training_zL3_Max], [IsDefault_Training_zL2_Max], [Training_zL2_Max], [IsDefault_Training_zL1_Max], [Training_zL1_Max], [TS6], [GUID] FROM [Jackpot].[dbo].[RaceHorse_old] 

GO


