USE [master]
GO

DROP DATABASE [Jackpot_33328]
GO

CREATE DATABASE [Jackpot_33328]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Jackpot_data_01', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_data_01.mdf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_data_02', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_data_02.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_data_03', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_data_03.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_data_04', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_data_04.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_data_05', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_data_05.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_data_06', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_data_06.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_data_07', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_data_07.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_data_08', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_data_08.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_data_09', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_data_09.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_data_10', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_data_10.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_data_11', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_data_11.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_data_12', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_data_12.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ), 
 FILEGROUP [INDEX]  DEFAULT
( NAME = N'Jackpot_index_01', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_index_01.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_index_02', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_index_02.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_index_03', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_index_03.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_index_04', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_index_04.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_index_05', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_index_05.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_index_06', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_index_06.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_index_07', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_index_07.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_index_08', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_index_08.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_index_09', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_index_09.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_index_10', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_index_10.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_index_11', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_index_11.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB ),
( NAME = N'Jackpot_index_12', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_index_12.ndf' , SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB )
 LOG ON 
( NAME = N'Jackpot_log_01', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_log_01.ldf' , SIZE = 1GB , MAXSIZE = 2048GB , FILEGROWTH = 1GB ), 
( NAME = N'Jackpot_log_02', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_log_02.ldf' , SIZE = 1GB , MAXSIZE = 2048GB , FILEGROWTH = 1GB ), 
( NAME = N'Jackpot_log_03', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_log_03.ldf' , SIZE = 1GB , MAXSIZE = 2048GB , FILEGROWTH = 1GB ), 
( NAME = N'Jackpot_log_04', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_log_04.ldf' , SIZE = 1GB , MAXSIZE = 2048GB , FILEGROWTH = 1GB ), 
( NAME = N'Jackpot_log_05', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_log_05.ldf' , SIZE = 1GB , MAXSIZE = 2048GB , FILEGROWTH = 1GB ), 
( NAME = N'Jackpot_log_06', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_log_06.ldf' , SIZE = 1GB , MAXSIZE = 2048GB , FILEGROWTH = 1GB ), 
( NAME = N'Jackpot_log_07', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_log_07.ldf' , SIZE = 1GB , MAXSIZE = 2048GB , FILEGROWTH = 1GB ), 
( NAME = N'Jackpot_log_08', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_log_08.ldf' , SIZE = 1GB , MAXSIZE = 2048GB , FILEGROWTH = 1GB ), 
( NAME = N'Jackpot_log_09', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_log_09.ldf' , SIZE = 1GB , MAXSIZE = 2048GB , FILEGROWTH = 1GB ), 
( NAME = N'Jackpot_log_10', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_log_10.ldf' , SIZE = 1GB , MAXSIZE = 2048GB , FILEGROWTH = 1GB ), 
( NAME = N'Jackpot_log_11', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_log_11.ldf' , SIZE = 1GB , MAXSIZE = 2048GB , FILEGROWTH = 1GB ), 
( NAME = N'Jackpot_log_12', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Jackpot_33328_log_12.ldf' , SIZE = 1GB , MAXSIZE = 2048GB , FILEGROWTH = 1GB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

ALTER DATABASE [Jackpot_33328] MODIFY FILEGROUP [INDEX] AUTOGROW_ALL_FILES
GO

ALTER DATABASE [Jackpot_33328] MODIFY FILEGROUP [PRIMARY] AUTOGROW_ALL_FILES
GO


