USE Jackpot33331
GO
--DELETE FROM PredictByBracket
--DELETE FROM PredictByExacta
--DELETE FROM PredictByPlace
--DELETE FROM PredictByQuinella
--DELETE FROM PredictByTrifecta
--DELETE FROM PredictByTrio
--DELETE FROM PredictByWide
--DELETE FROM PredictByWin
--
DELETE FROM OddsByBracket
DELETE FROM OddsByExacta
DELETE FROM OddsByPlace
DELETE FROM OddsByQuinella
DELETE FROM OddsByTrifecta
DELETE FROM OddsByTrio
DELETE FROM OddsByWide
DELETE FROM OddsByWin
--
DELETE FROM Odds1
DELETE FROM Odds2
DELETE FROM Odds3
DELETE FROM Odds4
DELETE FROM Odds5
DELETE FROM Odds6
GO