TRUNCATE TABLE PredictByBracket
TRUNCATE TABLE PredictByExacta
TRUNCATE TABLE PredictByPlace
TRUNCATE TABLE PredictByQuinella
TRUNCATE TABLE PredictByTrifecta
TRUNCATE TABLE PredictByTrio
TRUNCATE TABLE PredictByWide
TRUNCATE TABLE PredictByWin
--
TRUNCATE TABLE OddsByBracket
TRUNCATE TABLE OddsByExacta
TRUNCATE TABLE OddsByPlace
TRUNCATE TABLE OddsByQuinella
TRUNCATE TABLE OddsByTrifecta
TRUNCATE TABLE OddsByTrio
TRUNCATE TABLE OddsByWide
TRUNCATE TABLE OddsByWin
--
--TRUNCATE TABLE Odds1
--TRUNCATE TABLE Odds2
--TRUNCATE TABLE Odds3
--TRUNCATE TABLE Odds4
--TRUNCATE TABLE Odds5
--TRUNCATE TABLE Odds6
--
DELETE FROM Odds1
DELETE FROM Odds2
DELETE FROM Odds3
DELETE FROM Odds4
DELETE FROM Odds5
DELETE FROM Odds6