USE Jackpot
GO
TRUNCATE TABLE AnalysisAllOfChildren01ByJyokenGradeTrackType
TRUNCATE TABLE AnalysisAllOfChildren02ByJyokenGradeTrackType
TRUNCATE TABLE AnalysisAllOfHorseByAll
TRUNCATE TABLE AnalysisAllOfHorseByJyokenGradeTrackType
TRUNCATE TABLE AnalysisAllOfHorseByTrackType
TRUNCATE TABLE AnalysisAllOfJockyByJyokenGradeTrackType
TRUNCATE TABLE AnalysisPred1OfChildren01ByJyokenGradeTrackType
TRUNCATE TABLE AnalysisPred1OfChildren02ByJyokenGradeTrackType
TRUNCATE TABLE AnalysisPred1OfHorseByAll
TRUNCATE TABLE AnalysisPred1OfHorseByJyokenGradeTrackType
TRUNCATE TABLE AnalysisPred1OfHorseByTrackType
TRUNCATE TABLE AnalysisPred1OfJockyByJyokenGradeTrackType
TRUNCATE TABLE AnalysisPred2OfChildren01ByJyokenGradeTrackType
TRUNCATE TABLE AnalysisPred2OfChildren02ByJyokenGradeTrackType
TRUNCATE TABLE AnalysisPred2OfHorseByAll
TRUNCATE TABLE AnalysisPred2OfHorseByJyokenGradeTrackType
TRUNCATE TABLE AnalysisPred2OfHorseByTrackType
TRUNCATE TABLE AnalysisPred2OfJockyByJyokenGradeTrackType
TRUNCATE TABLE AnalysisSimOfHorseByAll