ALTER TABLE Hansyoku REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO



ALTER TABLE WinFive REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE WinFiveByPay REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE WinFiveByRace REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE WinFiveByYuko REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_DataMining_DmTime_L4 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_DataMiningTaisen_TmScore_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_HansyokuTotal01 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_HansyokuTotal02 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Odds1ByWin_ApprovalRateWin_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Odds1ByWin_ApprovalRateWinLog_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Odds1ByWin_BetCount_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Odds1ByWin_BetCountLog_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Odds1ByWin_NinkiRate_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Odds1ByWin_Odds1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Odds1ByWin_Odds1Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Odds1ByWin_OddsInverse1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Odds1ByWin_OddsInverse1Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Odds1ByWin_OddsRate1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Odds1ByWin_TotalBetCount_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Odds1ByWin_TotalBetCountLog_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_PayoffByPayAll_NinkiRate_L3 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_PayoffByPayAll_Pay_L3 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_PayoffByPayAll_PayLog_L3 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Race_Kyori_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Race_Kyori_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Race_S3_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Race_S3_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Race_S3Avg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Race_S3Avg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Race_S8_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Race_S8_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Race_S8Avg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Race_S8Avg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_Barei_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_BaTaijyu_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_Futan_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_FutanPercent_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_LifeTime_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_Ninki_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_Umaban_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_zBarei_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_zBaTaijyu_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_zFutan_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_zFutanPercent_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_zLifeTime_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_zNinki_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_ZogenPercent_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_ZogenSa_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_zTimeByRaceByMean_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_zTimeByRaceByMedian_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_zUmaban_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_zZogenPercent_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceHorse_zZogenSa_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByRunningStyle_RunningStyleAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_ApprovalRateWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_ApprovalRateWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_ExpectedValueWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_ExpectedValueWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_HitCount1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_HitCount12_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_HitCount123_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_HitCount123Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_HitCount12Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_HitCount1Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_HitRate1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_HitRate12_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_HitRate123_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_HitRate123Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_HitRate12Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_HitRate1Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_OddsWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_OddsWinInverseAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_OddsWinInverseLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_OddsWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_RunCount_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotal_RunCountLog_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotalByJyokenGradeCd_zTimeByRaceAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotalByJyokenGradeCd_zTimeByRaceLatest_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultByHorseByTotalByJyokenGradeCd_zTimeByRaceMax_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_ApprovalRateWinAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_ApprovalRateWinLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_ExpectedValueWinAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_ExpectedValueWinLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_HitCount1_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_HitCount12_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_HitCount123_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_HitCount123Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_HitCount12Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_HitCount1Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_HitRate1_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_HitRate12_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_HitRate123_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_HitRate123Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_HitRate12Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_HitRate1Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_OddsWinAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_OddsWinInverseAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_OddsWinInverseLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_OddsWinLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_RunCount_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_RunCountLog_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zApprovalRateWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zApprovalRateWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zExpectedValueWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zExpectedValueWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zHitCount1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zHitCount12_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zHitCount123_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zHitCount123Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zHitCount12Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zHitCount1Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zHitRate1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zHitRate12_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zHitRate123_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zHitRate123Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zHitRate12Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zHitRate1Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zOddsWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zOddsWinInverseAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zOddsWinInverseLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zOddsWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zRunCount_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zRunCountLog_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zStdTimeAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zStdTimeMin_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zzStdTimeAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal01_zzStdTimeMin_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_ApprovalRateWinAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_ApprovalRateWinLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_ExpectedValueWinAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_ExpectedValueWinLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_HitCount1_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_HitCount12_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_HitCount123_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_HitCount123Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_HitCount12Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_HitCount1Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_HitRate1_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_HitRate12_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_HitRate123_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_HitRate123Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_HitRate12Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_HitRate1Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_OddsWinAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_OddsWinInverseAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_OddsWinInverseLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_OddsWinLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_RunCount_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_RunCountLog_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zApprovalRateWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zApprovalRateWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zExpectedValueWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zExpectedValueWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zHitCount1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zHitCount12_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zHitCount123_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zHitCount123Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zHitCount12Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zHitCount1Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zHitRate1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zHitRate12_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zHitRate123_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zHitRate123Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zHitRate12Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zHitRate1Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zOddsWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zOddsWinInverseAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zOddsWinInverseLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zOddsWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zRunCount_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zRunCountLog_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zStdTimeAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zStdTimeMin_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zzStdTimeAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfChildrenByTotal02_zzStdTimeMin_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_ApprovalRateWinAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_ApprovalRateWinLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_ExpectedValueWinAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_ExpectedValueWinLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_HitCount1_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_HitCount12_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_HitCount123_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_HitCount123Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_HitCount12Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_HitCount1Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_HitRate1_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_HitRate12_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_HitRate123_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_HitRate123Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_HitRate12Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_HitRate1Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_OddsWinAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_OddsWinInverseAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_OddsWinInverseLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_OddsWinLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_RunCount_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_RunCountLog_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zApprovalRateWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zApprovalRateWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zExpectedValueWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zExpectedValueWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zHitCount1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zHitCount12_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zHitCount123_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zHitCount123Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zHitCount12Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zHitCount1Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zHitRate1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zHitRate12_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zHitRate123_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zHitRate123Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zHitRate12Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zHitRate1Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zOddsWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zOddsWinInverseAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zOddsWinInverseLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zOddsWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zRunCount_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zRunCountLog_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zStdTimeAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zStdTimeMin_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zzStdTimeAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfJockyByTotal_zzStdTimeMin_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_ApprovalRateWinAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_ApprovalRateWinLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_ExpectedValueWinAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_ExpectedValueWinLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_HitCount1_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_HitCount12_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_HitCount123_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_HitCount123Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_HitCount12Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_HitCount1Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_HitRate1_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_HitRate12_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_HitRate123_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_HitRate123Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_HitRate12Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_HitRate1Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_OddsWinAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_OddsWinInverseAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_OddsWinInverseLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_OddsWinLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_RunCount_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_RunCountLog_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zApprovalRateWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zApprovalRateWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zExpectedValueWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zExpectedValueWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zHitCount1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zHitCount12_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zHitCount123_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zHitCount123Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zHitCount12Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zHitCount1Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zHitRate1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zHitRate12_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zHitRate123_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zHitRate123Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zHitRate12Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zHitRate1Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zOddsWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zOddsWinInverseAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zOddsWinInverseLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zOddsWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zRunCount_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zRunCountLog_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zStdTimeAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zStdTimeMin_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zzStdTimeAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal01_zzStdTimeMin_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_ApprovalRateWinAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_ApprovalRateWinLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_ExpectedValueWinAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_ExpectedValueWinLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_HitCount1_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_HitCount12_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_HitCount123_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_HitCount123Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_HitCount12Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_HitCount1Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_HitRate1_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_HitRate12_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_HitRate123_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_HitRate123Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_HitRate12Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_HitRate1Log_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_OddsWinAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_OddsWinInverseAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_OddsWinInverseLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_OddsWinLogAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_RunCount_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_RunCountLog_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zApprovalRateWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zApprovalRateWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zExpectedValueWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zExpectedValueWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zHitCount1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zHitCount12_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zHitCount123_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zHitCount123Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zHitCount12Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zHitCount1Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zHitRate1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zHitRate12_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zHitRate123_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zHitRate123Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zHitRate12Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zHitRate1Log_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zOddsWinAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zOddsWinInverseAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zOddsWinInverseLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zOddsWinLogAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zRunCount_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zRunCountLog_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zStdTimeAvg_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zStdTimeMin_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zzStdTimeAvg_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_RaceResultOfParentsByTotal02_zzStdTimeMin_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Training_H2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Training_H3 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Training_H4 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Training_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Training_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Training_L3 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_Training_L4 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_zTraining_zH2_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_zTraining_zH2_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_zTraining_zH3_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_zTraining_zH3_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_zTraining_zH4_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_zTraining_zH4_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_zTraining_zL1_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_zTraining_zL1_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_zTraining_zL2_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_zTraining_zL2_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_zTraining_zL3_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_zTraining_zL3_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_zTraining_zL4_L1 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zBaseStats_zTraining_zL4_L2 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zValidStats_Race_S3 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO

ALTER TABLE zValidStats_Race_S8 REBUILD PARTITION = ALL WITH ( DATA_COMPRESSION = PAGE )
GO
		