USE [Jackpot]
GO

EXEC dbo.sp_rename @objname = N'[dbo].[RaceResultByHorseByTotal]', @newname = N'RaceResultByHorseByTotal_old', @objtype = N'OBJECT'
GO

USE [Jackpot]
GO

EXEC [Jackpot].dbo.sp_rename @objname = N'[dbo].[DF_RaceResultByHorseByTotal_GUID]', @newname = N'DF_RaceResultByHorseByTotal_GUIDOnRaceResultByHorseByTotal_old', @objtype = N'OBJECT'
GO

USE [Jackpot]
GO

SET ANSI_NULLS ON
GO

CREATE TABLE [dbo].[RaceResultByHorseByTotal]
(
	[RecordSpec] [char](2) COLLATE Japanese_CI_AS NULL,
	[DataKubun] [char](1) COLLATE Japanese_CI_AS NULL,
	[MakeDate] [date] NULL,
	[RaceDate] [date] NULL,
	[JyoCD] [char](2) COLLATE Japanese_CI_AS NOT NULL,
	[Kaiji] [int] NULL,
	[Nichiji] [int] NULL,
	[RaceNum] [int] NULL,
	[RaceID] [char](20) COLLATE Japanese_CI_AS NOT NULL,
	[KettoNum] [char](10) COLLATE Japanese_CI_AS NOT NULL,
	[RunCount] [float](53) NULL,
	[HitCount1] [float](53) NULL,
	[HitRate1] [float](53) NULL,
	[HitCount2] [float](53) NULL,
	[HitRate2] [float](53) NULL,
	[HitCount3] [float](53) NULL,
	[HitRate3] [float](53) NULL,
	[HitCount4] [float](53) NULL,
	[HitRate4] [float](53) NULL,
	[HitCount5] [float](53) NULL,
	[HitRate5] [float](53) NULL,
	[HitCount6] [float](53) NULL,
	[HitRate6] [float](53) NULL,
	[RunCountTotal] [float](53) NULL,
	[HitCountTotal1] [float](53) NULL,
	[HitRateTotal1] [float](53) NULL,
	[HitCountTotal2] [float](53) NULL,
	[HitRateTotal2] [float](53) NULL,
	[HitCountTotal3] [float](53) NULL,
	[HitRateTotal3] [float](53) NULL,
	[HitCountTotal4] [float](53) NULL,
	[HitRateTotal4] [float](53) NULL,
	[HitCountTotal5] [float](53) NULL,
	[HitRateTotal5] [float](53) NULL,
	[HitCountTotal6] [float](53) NULL,
	[HitRateTotal6] [float](53) NULL,
	[TS] [datetime2](7) NULL,
	[DeviateCount1] [float](53) NULL,
	[DeviateRate1] [float](53) NULL,
	[DeviateCount123] [float](53) NULL,
	[DeviateRate123] [float](53) NULL,
	[RunCountSlope] [float](53) NULL,
	[HitCountSlope1] [float](53) NULL,
	[HitRateSlope1] [float](53) NULL,
	[DeviateCountSlope1] [float](53) NULL,
	[DeviateRateSlope1] [float](53) NULL,
	[HitCountSlope123] [float](53) NULL,
	[HitRateSlope123] [float](53) NULL,
	[DeviateCountSlope123] [float](53) NULL,
	[DeviateRateSlope123] [float](53) NULL,
	[RunCountSmallTurn] [float](53) NULL,
	[HitCountSmallTurn1] [float](53) NULL,
	[HitRateSmallTurn1] [float](53) NULL,
	[DeviateCountSmallTurn1] [float](53) NULL,
	[DeviateRateSmallTurn1] [float](53) NULL,
	[HitCountSmallTurn123] [float](53) NULL,
	[HitRateSmallTurn123] [float](53) NULL,
	[DeviateCountSmallTurn123] [float](53) NULL,
	[DeviateRateSmallTurn123] [float](53) NULL,
	[RunCountTrackStraight] [float](53) NULL,
	[HitCountTrackStraight1] [float](53) NULL,
	[HitRateTrackStraight1] [float](53) NULL,
	[DeviateCountTrackStraight1] [float](53) NULL,
	[DeviateRateTrackStraight1] [float](53) NULL,
	[HitCountTrackStraight123] [float](53) NULL,
	[HitRateTrackStraight123] [float](53) NULL,
	[DeviateCountTrackStraight123] [float](53) NULL,
	[DeviateRateTrackStraight123] [float](53) NULL,
	[RunCountTrackLeft] [float](53) NULL,
	[HitCountTrackLeft1] [float](53) NULL,
	[HitRateTrackLeft1] [float](53) NULL,
	[DeviateCountTrackLeft1] [float](53) NULL,
	[DeviateRateTrackLeft1] [float](53) NULL,
	[HitCountTrackLeft123] [float](53) NULL,
	[HitRateTrackLeft123] [float](53) NULL,
	[DeviateCountTrackLeft123] [float](53) NULL,
	[DeviateRateTrackLeft123] [float](53) NULL,
	[RunCountTrackRight] [float](53) NULL,
	[HitCountTrackRight1] [float](53) NULL,
	[HitRateTrackRight1] [float](53) NULL,
	[DeviateCountTrackRight1] [float](53) NULL,
	[DeviateRateTrackRight1] [float](53) NULL,
	[HitCountTrackRight123] [float](53) NULL,
	[HitRateTrackRight123] [float](53) NULL,
	[DeviateCountTrackRight123] [float](53) NULL,
	[DeviateRateTrackRight123] [float](53) NULL,
	[HitCount12] [float](53) NULL,
	[HitRate12] [float](53) NULL,
	[HitCount123] [float](53) NULL,
	[HitRate123] [float](53) NULL,
	[HitCountTotal12] [float](53) NULL,
	[HitRateTotal12] [float](53) NULL,
	[HitCountTotal123] [float](53) NULL,
	[HitRateTotal123] [float](53) NULL,
	[RunCountLog] [float](53) NULL,
	[HitCount1Log] [float](53) NULL,
	[HitRate1Log] [float](53) NULL,
	[HitCount2Log] [float](53) NULL,
	[HitRate2Log] [float](53) NULL,
	[HitCount3Log] [float](53) NULL,
	[HitRate3Log] [float](53) NULL,
	[HitCount4Log] [float](53) NULL,
	[HitRate4Log] [float](53) NULL,
	[HitCount5Log] [float](53) NULL,
	[HitRate5Log] [float](53) NULL,
	[HitCount6Log] [float](53) NULL,
	[HitRate6Log] [float](53) NULL,
	[HitCount12Log] [float](53) NULL,
	[HitRate12Log] [float](53) NULL,
	[HitCount123Log] [float](53) NULL,
	[HitRate123Log] [float](53) NULL,
	[RunCountTotalLog] [float](53) NULL,
	[HitCountTotal1Log] [float](53) NULL,
	[HitRateTotal1Log] [float](53) NULL,
	[HitCountTotal2Log] [float](53) NULL,
	[HitRateTotal2Log] [float](53) NULL,
	[HitCountTotal3Log] [float](53) NULL,
	[HitRateTotal3Log] [float](53) NULL,
	[HitCountTotal4Log] [float](53) NULL,
	[HitRateTotal4Log] [float](53) NULL,
	[HitCountTotal5Log] [float](53) NULL,
	[HitRateTotal5Log] [float](53) NULL,
	[HitCountTotal6Log] [float](53) NULL,
	[HitRateTotal6Log] [float](53) NULL,
	[HitCountTotal12Log] [float](53) NULL,
	[HitRateTotal12Log] [float](53) NULL,
	[HitCountTotal123Log] [float](53) NULL,
	[HitRateTotal123Log] [float](53) NULL,
	[OddsWin] [float](53) NULL,
	[OddsWinLog] [float](53) NULL,
	[OddsPlace1] [float](53) NULL,
	[OddsPlace1Log] [float](53) NULL,
	[OddsPlace2] [float](53) NULL,
	[OddsPlace2Log] [float](53) NULL,
	[OddsWinInverse] [float](53) NULL,
	[OddsPlaceInverse1] [float](53) NULL,
	[OddsPlaceInverse2] [float](53) NULL,
	[OddsWinInverseLog] [float](53) NULL,
	[OddsPlaceInverse1Log] [float](53) NULL,
	[OddsPlaceInverse2Log] [float](53) NULL,
	[ApprovalRateWin] [float](53) NULL,
	[ApprovalRateWinLog] [float](53) NULL,
	[ApprovalRatePlace1] [float](53) NULL,
	[ApprovalRatePlace1Log] [float](53) NULL,
	[ApprovalRatePlace2] [float](53) NULL,
	[ApprovalRatePlace2Log] [float](53) NULL,
	[ExpectedValueWin] [float](53) NULL,
	[ExpectedValueWinLog] [float](53) NULL,
	[ExpectedValuePlace] [float](53) NULL,
	[ExpectedValuePlaceLog] [float](53) NULL,
	[StdTime] [float](53) NULL,
	[StdTimeDev] [float](53) NULL,
	[StdTimeDevMin] [float](53) NULL,
	[StdTimeDevMax] [float](53) NULL,
	[TS2] [datetime2](7) NULL,
	[GUID] [uniqueidentifier] NULL,

 CONSTRAINT [RaceResultByHorseByTotal_éÂÉLÅ[]  PRIMARY KEY NONCLUSTERED HASH 
(
	[RaceID],
	[KettoNum]
)WITH ( BUCKET_COUNT = 1048576)
)WITH ( MEMORY_OPTIMIZED = ON , DURABILITY = SCHEMA_AND_DATA )

GO

ALTER TABLE [dbo].[RaceResultByHorseByTotal] ADD  CONSTRAINT [DF_RaceResultByHorseByTotal_GUID]  DEFAULT (newid()) FOR [GUID]
GO

INSERT INTO [Jackpot].[dbo].[RaceResultByHorseByTotal] ([RecordSpec], [DataKubun], [MakeDate], [RaceDate], [JyoCD], [Kaiji], [Nichiji], [RaceNum], [RaceID], [KettoNum], [RunCount], [HitCount1], [HitRate1], [HitCount2], [HitRate2], [HitCount3], [HitRate3], [HitCount4], [HitRate4], [HitCount5], [HitRate5], [HitCount6], [HitRate6], [RunCountTotal], [HitCountTotal1], [HitRateTotal1], [HitCountTotal2], [HitRateTotal2], [HitCountTotal3], [HitRateTotal3], [HitCountTotal4], [HitRateTotal4], [HitCountTotal5], [HitRateTotal5], [HitCountTotal6], [HitRateTotal6], [TS], [DeviateCount1], [DeviateRate1], [DeviateCount123], [DeviateRate123], [RunCountSlope], [HitCountSlope1], [HitRateSlope1], [DeviateCountSlope1], [DeviateRateSlope1], [HitCountSlope123], [HitRateSlope123], [DeviateCountSlope123], [DeviateRateSlope123], [RunCountSmallTurn], [HitCountSmallTurn1], [HitRateSmallTurn1], [DeviateCountSmallTurn1], [DeviateRateSmallTurn1], [HitCountSmallTurn123], [HitRateSmallTurn123], [DeviateCountSmallTurn123], [DeviateRateSmallTurn123], [RunCountTrackStraight], [HitCountTrackStraight1], [HitRateTrackStraight1], [DeviateCountTrackStraight1], [DeviateRateTrackStraight1], [HitCountTrackStraight123], [HitRateTrackStraight123], [DeviateCountTrackStraight123], [DeviateRateTrackStraight123], [RunCountTrackLeft], [HitCountTrackLeft1], [HitRateTrackLeft1], [DeviateCountTrackLeft1], [DeviateRateTrackLeft1], [HitCountTrackLeft123], [HitRateTrackLeft123], [DeviateCountTrackLeft123], [DeviateRateTrackLeft123], [RunCountTrackRight], [HitCountTrackRight1], [HitRateTrackRight1], [DeviateCountTrackRight1], [DeviateRateTrackRight1], [HitCountTrackRight123], [HitRateTrackRight123], [DeviateCountTrackRight123], [DeviateRateTrackRight123], [HitCount12], [HitRate12], [HitCount123], [HitRate123], [HitCountTotal12], [HitRateTotal12], [HitCountTotal123], [HitRateTotal123], [RunCountLog], [HitCount1Log], [HitRate1Log], [HitCount2Log], [HitRate2Log], [HitCount3Log], [HitRate3Log], [HitCount4Log], [HitRate4Log], [HitCount5Log], [HitRate5Log], [HitCount6Log], [HitRate6Log], [HitCount12Log], [HitRate12Log], [HitCount123Log], [HitRate123Log], [RunCountTotalLog], [HitCountTotal1Log], [HitRateTotal1Log], [HitCountTotal2Log], [HitRateTotal2Log], [HitCountTotal3Log], [HitRateTotal3Log], [HitCountTotal4Log], [HitRateTotal4Log], [HitCountTotal5Log], [HitRateTotal5Log], [HitCountTotal6Log], [HitRateTotal6Log], [HitCountTotal12Log], [HitRateTotal12Log], [HitCountTotal123Log], [HitRateTotal123Log], [OddsWin], [OddsWinLog], [OddsPlace1], [OddsPlace1Log], [OddsPlace2], [OddsPlace2Log], [OddsWinInverse], [OddsPlaceInverse1], [OddsPlaceInverse2], [OddsWinInverseLog], [OddsPlaceInverse1Log], [OddsPlaceInverse2Log], [ApprovalRateWin], [ApprovalRateWinLog], [ApprovalRatePlace1], [ApprovalRatePlace1Log], [ApprovalRatePlace2], [ApprovalRatePlace2Log], [ExpectedValueWin], [ExpectedValueWinLog], [ExpectedValuePlace], [ExpectedValuePlaceLog], [StdTime], [StdTimeDev], [StdTimeDevMin], [StdTimeDevMax], [TS2], [GUID]) SELECT [RecordSpec], [DataKubun], [MakeDate], [RaceDate], [JyoCD], [Kaiji], [Nichiji], [RaceNum], [RaceID], [KettoNum], [RunCount], [HitCount1], [HitRate1], [HitCount2], [HitRate2], [HitCount3], [HitRate3], [HitCount4], [HitRate4], [HitCount5], [HitRate5], [HitCount6], [HitRate6], [RunCountTotal], [HitCountTotal1], [HitRateTotal1], [HitCountTotal2], [HitRateTotal2], [HitCountTotal3], [HitRateTotal3], [HitCountTotal4], [HitRateTotal4], [HitCountTotal5], [HitRateTotal5], [HitCountTotal6], [HitRateTotal6], [TS], [DeviateCount1], [DeviateRate1], [DeviateCount123], [DeviateRate123], [RunCountSlope], [HitCountSlope1], [HitRateSlope1], [DeviateCountSlope1], [DeviateRateSlope1], [HitCountSlope123], [HitRateSlope123], [DeviateCountSlope123], [DeviateRateSlope123], [RunCountSmallTurn], [HitCountSmallTurn1], [HitRateSmallTurn1], [DeviateCountSmallTurn1], [DeviateRateSmallTurn1], [HitCountSmallTurn123], [HitRateSmallTurn123], [DeviateCountSmallTurn123], [DeviateRateSmallTurn123], [RunCountTrackStraight], [HitCountTrackStraight1], [HitRateTrackStraight1], [DeviateCountTrackStraight1], [DeviateRateTrackStraight1], [HitCountTrackStraight123], [HitRateTrackStraight123], [DeviateCountTrackStraight123], [DeviateRateTrackStraight123], [RunCountTrackLeft], [HitCountTrackLeft1], [HitRateTrackLeft1], [DeviateCountTrackLeft1], [DeviateRateTrackLeft1], [HitCountTrackLeft123], [HitRateTrackLeft123], [DeviateCountTrackLeft123], [DeviateRateTrackLeft123], [RunCountTrackRight], [HitCountTrackRight1], [HitRateTrackRight1], [DeviateCountTrackRight1], [DeviateRateTrackRight1], [HitCountTrackRight123], [HitRateTrackRight123], [DeviateCountTrackRight123], [DeviateRateTrackRight123], [HitCount12], [HitRate12], [HitCount123], [HitRate123], [HitCountTotal12], [HitRateTotal12], [HitCountTotal123], [HitRateTotal123], [RunCountLog], [HitCount1Log], [HitRate1Log], [HitCount2Log], [HitRate2Log], [HitCount3Log], [HitRate3Log], [HitCount4Log], [HitRate4Log], [HitCount5Log], [HitRate5Log], [HitCount6Log], [HitRate6Log], [HitCount12Log], [HitRate12Log], [HitCount123Log], [HitRate123Log], [RunCountTotalLog], [HitCountTotal1Log], [HitRateTotal1Log], [HitCountTotal2Log], [HitRateTotal2Log], [HitCountTotal3Log], [HitRateTotal3Log], [HitCountTotal4Log], [HitRateTotal4Log], [HitCountTotal5Log], [HitRateTotal5Log], [HitCountTotal6Log], [HitRateTotal6Log], [HitCountTotal12Log], [HitRateTotal12Log], [HitCountTotal123Log], [HitRateTotal123Log], [OddsWin], [OddsWinLog], [OddsPlace1], [OddsPlace1Log], [OddsPlace2], [OddsPlace2Log], [OddsWinInverse], [OddsPlaceInverse1], [OddsPlaceInverse2], [OddsWinInverseLog], [OddsPlaceInverse1Log], [OddsPlaceInverse2Log], [ApprovalRateWin], [ApprovalRateWinLog], [ApprovalRatePlace1], [ApprovalRatePlace1Log], [ApprovalRatePlace2], [ApprovalRatePlace2Log], [ExpectedValueWin], [ExpectedValueWinLog], [ExpectedValuePlace], [ExpectedValuePlaceLog], [StdTime], [StdTimeDev], [StdTimeDevMin], [StdTimeDevMax], [TS2], [GUID] FROM [Jackpot].[dbo].[RaceResultByHorseByTotal_old] 

GO


