USE [Jackpot];
GO
BEGIN TRANSACTION;
CREATE CLUSTERED INDEX [ClusteredIndex_on_PS_Date_636027070049483574] ON [dbo].[Bet1]([RaceDate]) WITH(SORT_IN_TEMPDB = ON, DROP_EXISTING = OFF, ONLINE = OFF) ON [PS_Date]([RaceDate]);
DROP INDEX [ClusteredIndex_on_PS_Date_636027070049483574] ON [dbo].[Bet1];
CREATE UNIQUE NONCLUSTERED INDEX [IX_Bet1] ON [dbo].[Bet1]([RaceDate] DESC, [JyoCD] ASC, [Kaiji] ASC, [Nichiji] ASC, [RaceNum] ASC) WITH(PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate]);
COMMIT TRANSACTION;