USE [Jackpot]
GO
BEGIN TRANSACTION
ALTER TABLE [dbo].[Bet6ByHenkanUma] DROP CONSTRAINT [FK_Bet6ByHenkanUma_Bet6]






ALTER TABLE [dbo].[Bet6] DROP CONSTRAINT [PK_Bet6]


ALTER TABLE [dbo].[Bet6] ADD  CONSTRAINT [PK_Bet6] PRIMARY KEY NONCLUSTERED 
(
	[RaceID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PS_Date_636027278734854813] ON [dbo].[Bet6]
(
	[RaceDate]
)WITH (SORT_IN_TEMPDB = ON, DROP_EXISTING = OFF, ONLINE = OFF) ON [PS_Date]([RaceDate])


DROP INDEX [ClusteredIndex_on_PS_Date_636027278734854813] ON [dbo].[Bet6]




ALTER TABLE [dbo].[Bet6ByHenkanUma]  WITH NOCHECK ADD  CONSTRAINT [FK_Bet6ByHenkanUma_Bet6] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Bet6] ([RaceID])
ALTER TABLE [dbo].[Bet6ByHenkanUma] NOCHECK CONSTRAINT [FK_Bet6ByHenkanUma_Bet6]






CREATE UNIQUE NONCLUSTERED INDEX [IX_Bet6] ON [dbo].[Bet6]
(
	[RaceDate] DESC,
	[JyoCD] ASC,
	[Kaiji] ASC,
	[Nichiji] ASC,
	[RaceNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])






COMMIT TRANSACTION



