USE [Jackpot]
GO
BEGIN TRANSACTION




ALTER TABLE [dbo].[DataMining] DROP CONSTRAINT [PK_DataMining]


ALTER TABLE [dbo].[DataMining] ADD  CONSTRAINT [PK_DataMining] PRIMARY KEY NONCLUSTERED 
(
	[RaceID] DESC,
	[Umaban] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PS_Date_636027881308537348] ON [dbo].[DataMining]
(
	[RaceDate]
)WITH (SORT_IN_TEMPDB = ON, DROP_EXISTING = OFF, ONLINE = OFF) ON [PS_Date]([RaceDate])


DROP INDEX [ClusteredIndex_on_PS_Date_636027881308537348] ON [dbo].[DataMining]








CREATE UNIQUE NONCLUSTERED INDEX [IX_DataMining] ON [dbo].[DataMining]
(
	[RaceDate] DESC,
	[JyoCD] ASC,
	[Kaiji] ASC,
	[Nichiji] ASC,
	[RaceNum] ASC,
	[Umaban] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_DataMining_Include01] ON [dbo].[DataMining]
(
	[DMTime] ASC
)
INCLUDE ( 	[RaceID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])






COMMIT TRANSACTION



