USE [Jackpot]
GO
BEGIN TRANSACTION




ALTER TABLE [dbo].[MgmtBetHistoryMaster] DROP CONSTRAINT [PK_MgmtBetHistory]


ALTER TABLE [dbo].[MgmtBetHistoryMaster] ADD  CONSTRAINT [PK_MgmtBetHistory] PRIMARY KEY NONCLUSTERED 
(
	[BetDateTime] DESC,
	[ReceptID] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PS_Date_636028179352328993] ON [dbo].[MgmtBetHistoryMaster]
(
	[RaceDate]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PS_Date]([RaceDate])


DROP INDEX [ClusteredIndex_on_PS_Date_636028179352328993] ON [dbo].[MgmtBetHistoryMaster]








CREATE UNIQUE NONCLUSTERED INDEX [IX_MgmtBetHistoryMaster] ON [dbo].[MgmtBetHistoryMaster]
(
	[BetDateTime] ASC,
	[RaceDate] DESC,
	[JyoCD] ASC,
	[Kaiji] ASC,
	[Nichiji] ASC,
	[RaceNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])






COMMIT TRANSACTION



