USE [Jackpot]
GO
BEGIN TRANSACTION




ALTER TABLE [dbo].[MgmtBet] DROP CONSTRAINT [PK_MgmtBet]


ALTER TABLE [dbo].[MgmtBet] ADD  CONSTRAINT [PK_MgmtBet] PRIMARY KEY NONCLUSTERED 
(
	[RaceID] DESC,
	[BetTypeCD] ASC,
	[BetDateTime] DESC,
	[Kumi1] ASC,
	[Kumi2] ASC,
	[Kumi3] ASC,
	[BetNum] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PS_Date_636028178411437133] ON [dbo].[MgmtBet]
(
	[RaceDate]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PS_Date]([RaceDate])


DROP INDEX [ClusteredIndex_on_PS_Date_636028178411437133] ON [dbo].[MgmtBet]








CREATE UNIQUE NONCLUSTERED INDEX [IX_MgmtBet] ON [dbo].[MgmtBet]
(
	[RaceDate] DESC,
	[JyoCD] ASC,
	[Kaiji] ASC,
	[Nichiji] ASC,
	[RaceNum] ASC,
	[BetTypeCD] ASC,
	[BetDateTime] ASC,
	[Kumi1] ASC,
	[Kumi2] ASC,
	[Kumi3] ASC,
	[BetNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])






COMMIT TRANSACTION



