USE [Jackpot]
GO
BEGIN TRANSACTION
ALTER TABLE [dbo].[Odds1ByWin] DROP CONSTRAINT [FK_Odds1ByWin_Odds1]






ALTER TABLE [dbo].[Odds1] DROP CONSTRAINT [PK_Odds1]


ALTER TABLE [dbo].[Odds1] ADD  CONSTRAINT [PK_Odds1] PRIMARY KEY NONCLUSTERED 
(
	[RaceID] DESC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PS_Date_636027169347101784] ON [dbo].[Odds1]
(
	[RaceDate]
)WITH (SORT_IN_TEMPDB = ON, DROP_EXISTING = OFF, ONLINE = OFF) ON [PS_Date]([RaceDate])


DROP INDEX [ClusteredIndex_on_PS_Date_636027169347101784] ON [dbo].[Odds1]




ALTER TABLE [dbo].[Odds1ByWin]  WITH NOCHECK ADD  CONSTRAINT [FK_Odds1ByWin_Odds1] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Odds1] ([RaceID])
ALTER TABLE [dbo].[Odds1ByWin] NOCHECK CONSTRAINT [FK_Odds1ByWin_Odds1]






CREATE UNIQUE NONCLUSTERED INDEX [IX_Odds1] ON [dbo].[Odds1]
(
	[RaceDate] DESC,
	[JyoCD] ASC,
	[Kaiji] ASC,
	[Nichiji] ASC,
	[RaceNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])






COMMIT TRANSACTION



