USE [Jackpot]
GO
BEGIN TRANSACTION




ALTER TABLE [dbo].[PayoffByHenkanDoWaku] DROP CONSTRAINT [PK_PayoffByHenkanDoWaku]


ALTER TABLE [dbo].[PayoffByHenkanDoWaku] ADD  CONSTRAINT [PK_PayoffByHenkanDoWaku] PRIMARY KEY NONCLUSTERED 
(
	[RaceID] DESC,
	[Wakuban] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PS_Date_636027165651922743] ON [dbo].[PayoffByHenkanDoWaku]
(
	[RaceDate]
)WITH (SORT_IN_TEMPDB = ON, DROP_EXISTING = OFF, ONLINE = OFF) ON [PS_Date]([RaceDate])


DROP INDEX [ClusteredIndex_on_PS_Date_636027165651922743] ON [dbo].[PayoffByHenkanDoWaku]








CREATE UNIQUE NONCLUSTERED INDEX [IX_PayoffByHenkanDoWaku] ON [dbo].[PayoffByHenkanDoWaku]
(
	[RaceDate] DESC,
	[JyoCD] ASC,
	[Kaiji] ASC,
	[Nichiji] ASC,
	[RaceNum] ASC,
	[Wakuban] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])






COMMIT TRANSACTION



