USE [Jackpot]
GO
BEGIN TRANSACTION




ALTER TABLE [dbo].[PayoffByHenkanUma] DROP CONSTRAINT [PK_PayoffByHenkanUma]


ALTER TABLE [dbo].[PayoffByHenkanUma] ADD  CONSTRAINT [PK_PayoffByHenkanUma] PRIMARY KEY NONCLUSTERED 
(
	[RaceID] DESC,
	[Umaban] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PS_Date_636027166316948581] ON [dbo].[PayoffByHenkanUma]
(
	[RaceDate]
)WITH (SORT_IN_TEMPDB = ON, DROP_EXISTING = OFF, ONLINE = OFF) ON [PS_Date]([RaceDate])


DROP INDEX [ClusteredIndex_on_PS_Date_636027166316948581] ON [dbo].[PayoffByHenkanUma]








CREATE UNIQUE NONCLUSTERED INDEX [IX_PayoffByHenkanUma] ON [dbo].[PayoffByHenkanUma]
(
	[RaceDate] DESC,
	[JyoCD] ASC,
	[Kaiji] ASC,
	[Nichiji] ASC,
	[RaceNum] ASC,
	[Umaban] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])






COMMIT TRANSACTION



