USE [Jackpot]
GO
BEGIN TRANSACTION




ALTER TABLE [dbo].[PayoffByFlag] DROP CONSTRAINT [PK_PayoffByFlag]


ALTER TABLE [dbo].[PayoffByFlag] ADD  CONSTRAINT [PK_PayoffByFlag] PRIMARY KEY NONCLUSTERED 
(
	[RaceID] DESC,
	[Type] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PS_Date_636027163959123435] ON [dbo].[PayoffByFlag]
(
	[RaceDate]
)WITH (SORT_IN_TEMPDB = ON, DROP_EXISTING = OFF, ONLINE = OFF) ON [PS_Date]([RaceDate])


DROP INDEX [ClusteredIndex_on_PS_Date_636027163959123435] ON [dbo].[PayoffByFlag]








CREATE UNIQUE NONCLUSTERED INDEX [IX_PayoffByFlag] ON [dbo].[PayoffByFlag]
(
	[RaceDate] DESC,
	[JyoCD] ASC,
	[Kaiji] ASC,
	[Nichiji] ASC,
	[RaceNum] ASC,
	[Type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])






COMMIT TRANSACTION



