USE [Jackpot]
GO
BEGIN TRANSACTION




ALTER TABLE [dbo].[PayoffByHenkanWaku] DROP CONSTRAINT [PK_PayoffByHenkanWaku]


ALTER TABLE [dbo].[PayoffByHenkanWaku] ADD  CONSTRAINT [PK_PayoffByHenkanWaku] PRIMARY KEY NONCLUSTERED 
(
	[RaceID] DESC,
	[Wakuban] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PS_Date_636027167299432921] ON [dbo].[PayoffByHenkanWaku]
(
	[RaceDate]
)WITH (SORT_IN_TEMPDB = ON, DROP_EXISTING = OFF, ONLINE = OFF) ON [PS_Date]([RaceDate])


DROP INDEX [ClusteredIndex_on_PS_Date_636027167299432921] ON [dbo].[PayoffByHenkanWaku]








CREATE UNIQUE NONCLUSTERED INDEX [IX_PayoffByHenkanWaku] ON [dbo].[PayoffByHenkanWaku]
(
	[RaceDate] DESC,
	[JyoCD] ASC,
	[Kaiji] ASC,
	[Nichiji] ASC,
	[RaceNum] ASC,
	[Wakuban] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])






COMMIT TRANSACTION



