USE [Jackpot]
GO
BEGIN TRANSACTION
ALTER TABLE [dbo].[Bet1] DROP CONSTRAINT [FK_Bet1_Race1]


ALTER TABLE [dbo].[Bet1ByBracket] DROP CONSTRAINT [FK_Bet1ByBracket_Race]


ALTER TABLE [dbo].[Bet1ByExacta] DROP CONSTRAINT [FK_Bet1ByExacta_Race]


ALTER TABLE [dbo].[Bet1ByPlace] DROP CONSTRAINT [FK_Bet1ByPlace_Race]


ALTER TABLE [dbo].[Bet1ByQuinella] DROP CONSTRAINT [FK_Bet1ByQuinella_Race]


ALTER TABLE [dbo].[Bet1ByTrio] DROP CONSTRAINT [FK_Bet1ByTrio_Race]


ALTER TABLE [dbo].[Bet1ByWide] DROP CONSTRAINT [FK_Bet1ByWide_Race]


ALTER TABLE [dbo].[Bet1ByWin] DROP CONSTRAINT [FK_Bet1ByWin_Race]


ALTER TABLE [dbo].[Bet6] DROP CONSTRAINT [FK_Bet6_Race]


ALTER TABLE [dbo].[Bet6ByTrifecta] DROP CONSTRAINT [FK_Bet6ByTrifecta_Race]


ALTER TABLE [dbo].[DataMining] DROP CONSTRAINT [FK_DataMining_Race]


ALTER TABLE [dbo].[MgmtBet] DROP CONSTRAINT [FK_MgmtBet_Race]


ALTER TABLE [dbo].[MgmtSim] DROP CONSTRAINT [FK_MgmtSim_Race]


ALTER TABLE [dbo].[Odds1] DROP CONSTRAINT [FK_Odds1_Race]


ALTER TABLE [dbo].[Odds1ByBracket] DROP CONSTRAINT [FK_Odds1ByBracket_Race]


ALTER TABLE [dbo].[Odds1ByPlace] DROP CONSTRAINT [FK_Odds1ByPlace_Race]


ALTER TABLE [dbo].[Odds2] DROP CONSTRAINT [FK_Odds2_Race]


ALTER TABLE [dbo].[Odds2ByQuinella] DROP CONSTRAINT [FK_Odds2ByQuinella_Race]


ALTER TABLE [dbo].[Odds3] DROP CONSTRAINT [FK_Odds3_Race]


ALTER TABLE [dbo].[Odds3ByWide] DROP CONSTRAINT [FK_Odds3ByWide_Race]


ALTER TABLE [dbo].[Odds4] DROP CONSTRAINT [FK_Odds4_Race]


ALTER TABLE [dbo].[Odds4ByExacta] DROP CONSTRAINT [FK_Odds4ByExacta_Race]


ALTER TABLE [dbo].[Odds5] DROP CONSTRAINT [FK_Odds5_Race]


ALTER TABLE [dbo].[Odds5ByTrio] DROP CONSTRAINT [FK_Odds5ByTrio_Race]


ALTER TABLE [dbo].[Odds6] DROP CONSTRAINT [FK_Odds6_Race]


ALTER TABLE [dbo].[Odds6ByTrifecta] DROP CONSTRAINT [FK_Odds6ByTrifecta_Race]


ALTER TABLE [dbo].[Payoff] DROP CONSTRAINT [FK_Payoff_Race]


ALTER TABLE [dbo].[PayoffByFlag] DROP CONSTRAINT [FK_PayoffByFlag_Race]


ALTER TABLE [dbo].[PayoffByHenkanDoWaku] DROP CONSTRAINT [FK_PayoffByHenkanDoWaku_Race]


ALTER TABLE [dbo].[PayoffByHenkanUma] DROP CONSTRAINT [FK_PayoffByHenkanUma_Race]


ALTER TABLE [dbo].[PayoffByHenkanWaku] DROP CONSTRAINT [FK_PayoffByHenkanWaku_Race]


ALTER TABLE [dbo].[PayoffByPayAll] DROP CONSTRAINT [FK_PayoffByPayAll_Race]


ALTER TABLE [dbo].[RaceHorse] DROP CONSTRAINT [FK_RaceHorse_Race]


ALTER TABLE [dbo].[RaceHorseBet] DROP CONSTRAINT [FK_RaceHorseBet_Race]


ALTER TABLE [dbo].[RaceResultByJockyByDistanceType] DROP CONSTRAINT [FK_RaceResultByJockyByDistanceType_Race]


ALTER TABLE [dbo].[RaceResultByJockyByJyo] DROP CONSTRAINT [FK_RaceResultByJockyByJyo_Race]


ALTER TABLE [dbo].[RaceResultByJockyByTrackType] DROP CONSTRAINT [FK_RaceResultByJockyByTrackType_Race]


ALTER TABLE [dbo].[SpecialRace] DROP CONSTRAINT [FK_SpecialRace_Race]


ALTER TABLE [dbo].[SpecialRaceByHorse] DROP CONSTRAINT [FK_SpecialRaceByHorse_Race]






ALTER TABLE [dbo].[Race] DROP CONSTRAINT [PK_Race]


ALTER TABLE [dbo].[Race] ADD  CONSTRAINT [PK_Race] PRIMARY KEY NONCLUSTERED 
(
	[RaceID] DESC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PS_Date_636027088246243831] ON [dbo].[Race]
(
	[RaceDate]
)WITH (SORT_IN_TEMPDB = ON, DROP_EXISTING = OFF, ONLINE = OFF) ON [PS_Date]([RaceDate])


DROP INDEX [ClusteredIndex_on_PS_Date_636027088246243831] ON [dbo].[Race]




ALTER TABLE [dbo].[Bet1]  WITH NOCHECK ADD  CONSTRAINT [FK_Bet1_Race1] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Bet1] NOCHECK CONSTRAINT [FK_Bet1_Race1]


ALTER TABLE [dbo].[Bet1ByBracket]  WITH NOCHECK ADD  CONSTRAINT [FK_Bet1ByBracket_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Bet1ByBracket] NOCHECK CONSTRAINT [FK_Bet1ByBracket_Race]


ALTER TABLE [dbo].[Bet1ByExacta]  WITH NOCHECK ADD  CONSTRAINT [FK_Bet1ByExacta_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Bet1ByExacta] NOCHECK CONSTRAINT [FK_Bet1ByExacta_Race]


ALTER TABLE [dbo].[Bet1ByPlace]  WITH NOCHECK ADD  CONSTRAINT [FK_Bet1ByPlace_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Bet1ByPlace] NOCHECK CONSTRAINT [FK_Bet1ByPlace_Race]


ALTER TABLE [dbo].[Bet1ByQuinella]  WITH NOCHECK ADD  CONSTRAINT [FK_Bet1ByQuinella_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Bet1ByQuinella] NOCHECK CONSTRAINT [FK_Bet1ByQuinella_Race]


ALTER TABLE [dbo].[Bet1ByTrio]  WITH NOCHECK ADD  CONSTRAINT [FK_Bet1ByTrio_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Bet1ByTrio] NOCHECK CONSTRAINT [FK_Bet1ByTrio_Race]


ALTER TABLE [dbo].[Bet1ByWide]  WITH NOCHECK ADD  CONSTRAINT [FK_Bet1ByWide_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Bet1ByWide] NOCHECK CONSTRAINT [FK_Bet1ByWide_Race]


ALTER TABLE [dbo].[Bet1ByWin]  WITH NOCHECK ADD  CONSTRAINT [FK_Bet1ByWin_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Bet1ByWin] NOCHECK CONSTRAINT [FK_Bet1ByWin_Race]


ALTER TABLE [dbo].[Bet6]  WITH NOCHECK ADD  CONSTRAINT [FK_Bet6_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Bet6] NOCHECK CONSTRAINT [FK_Bet6_Race]


ALTER TABLE [dbo].[Bet6ByTrifecta]  WITH NOCHECK ADD  CONSTRAINT [FK_Bet6ByTrifecta_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Bet6ByTrifecta] NOCHECK CONSTRAINT [FK_Bet6ByTrifecta_Race]


ALTER TABLE [dbo].[DataMining]  WITH NOCHECK ADD  CONSTRAINT [FK_DataMining_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[DataMining] NOCHECK CONSTRAINT [FK_DataMining_Race]


ALTER TABLE [dbo].[MgmtBet]  WITH NOCHECK ADD  CONSTRAINT [FK_MgmtBet_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[MgmtBet] NOCHECK CONSTRAINT [FK_MgmtBet_Race]


ALTER TABLE [dbo].[MgmtSim]  WITH NOCHECK ADD  CONSTRAINT [FK_MgmtSim_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[MgmtSim] NOCHECK CONSTRAINT [FK_MgmtSim_Race]


ALTER TABLE [dbo].[Odds1]  WITH NOCHECK ADD  CONSTRAINT [FK_Odds1_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Odds1] NOCHECK CONSTRAINT [FK_Odds1_Race]


ALTER TABLE [dbo].[Odds1ByBracket]  WITH NOCHECK ADD  CONSTRAINT [FK_Odds1ByBracket_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Odds1ByBracket] NOCHECK CONSTRAINT [FK_Odds1ByBracket_Race]


ALTER TABLE [dbo].[Odds1ByPlace]  WITH NOCHECK ADD  CONSTRAINT [FK_Odds1ByPlace_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Odds1ByPlace] NOCHECK CONSTRAINT [FK_Odds1ByPlace_Race]


ALTER TABLE [dbo].[Odds2]  WITH NOCHECK ADD  CONSTRAINT [FK_Odds2_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Odds2] NOCHECK CONSTRAINT [FK_Odds2_Race]


ALTER TABLE [dbo].[Odds2ByQuinella]  WITH NOCHECK ADD  CONSTRAINT [FK_Odds2ByQuinella_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Odds2ByQuinella] NOCHECK CONSTRAINT [FK_Odds2ByQuinella_Race]


ALTER TABLE [dbo].[Odds3]  WITH NOCHECK ADD  CONSTRAINT [FK_Odds3_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Odds3] NOCHECK CONSTRAINT [FK_Odds3_Race]


ALTER TABLE [dbo].[Odds3ByWide]  WITH NOCHECK ADD  CONSTRAINT [FK_Odds3ByWide_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Odds3ByWide] NOCHECK CONSTRAINT [FK_Odds3ByWide_Race]


ALTER TABLE [dbo].[Odds4]  WITH NOCHECK ADD  CONSTRAINT [FK_Odds4_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Odds4] NOCHECK CONSTRAINT [FK_Odds4_Race]


ALTER TABLE [dbo].[Odds4ByExacta]  WITH NOCHECK ADD  CONSTRAINT [FK_Odds4ByExacta_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Odds4ByExacta] NOCHECK CONSTRAINT [FK_Odds4ByExacta_Race]


ALTER TABLE [dbo].[Odds5]  WITH NOCHECK ADD  CONSTRAINT [FK_Odds5_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Odds5] NOCHECK CONSTRAINT [FK_Odds5_Race]


ALTER TABLE [dbo].[Odds5ByTrio]  WITH NOCHECK ADD  CONSTRAINT [FK_Odds5ByTrio_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Odds5ByTrio] NOCHECK CONSTRAINT [FK_Odds5ByTrio_Race]


ALTER TABLE [dbo].[Odds6]  WITH NOCHECK ADD  CONSTRAINT [FK_Odds6_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Odds6] NOCHECK CONSTRAINT [FK_Odds6_Race]


ALTER TABLE [dbo].[Odds6ByTrifecta]  WITH NOCHECK ADD  CONSTRAINT [FK_Odds6ByTrifecta_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Odds6ByTrifecta] NOCHECK CONSTRAINT [FK_Odds6ByTrifecta_Race]


ALTER TABLE [dbo].[Payoff]  WITH NOCHECK ADD  CONSTRAINT [FK_Payoff_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[Payoff] NOCHECK CONSTRAINT [FK_Payoff_Race]


ALTER TABLE [dbo].[PayoffByFlag]  WITH NOCHECK ADD  CONSTRAINT [FK_PayoffByFlag_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[PayoffByFlag] NOCHECK CONSTRAINT [FK_PayoffByFlag_Race]


ALTER TABLE [dbo].[PayoffByHenkanDoWaku]  WITH NOCHECK ADD  CONSTRAINT [FK_PayoffByHenkanDoWaku_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[PayoffByHenkanDoWaku] NOCHECK CONSTRAINT [FK_PayoffByHenkanDoWaku_Race]


ALTER TABLE [dbo].[PayoffByHenkanUma]  WITH NOCHECK ADD  CONSTRAINT [FK_PayoffByHenkanUma_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[PayoffByHenkanUma] NOCHECK CONSTRAINT [FK_PayoffByHenkanUma_Race]


ALTER TABLE [dbo].[PayoffByHenkanWaku]  WITH NOCHECK ADD  CONSTRAINT [FK_PayoffByHenkanWaku_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[PayoffByHenkanWaku] NOCHECK CONSTRAINT [FK_PayoffByHenkanWaku_Race]


ALTER TABLE [dbo].[PayoffByPayAll]  WITH NOCHECK ADD  CONSTRAINT [FK_PayoffByPayAll_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[PayoffByPayAll] NOCHECK CONSTRAINT [FK_PayoffByPayAll_Race]


ALTER TABLE [dbo].[RaceHorse]  WITH NOCHECK ADD  CONSTRAINT [FK_RaceHorse_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[RaceHorse] NOCHECK CONSTRAINT [FK_RaceHorse_Race]


ALTER TABLE [dbo].[RaceHorseBet]  WITH NOCHECK ADD  CONSTRAINT [FK_RaceHorseBet_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[RaceHorseBet] NOCHECK CONSTRAINT [FK_RaceHorseBet_Race]


ALTER TABLE [dbo].[RaceResultByJockyByDistanceType]  WITH NOCHECK ADD  CONSTRAINT [FK_RaceResultByJockyByDistanceType_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[RaceResultByJockyByDistanceType] NOCHECK CONSTRAINT [FK_RaceResultByJockyByDistanceType_Race]


ALTER TABLE [dbo].[RaceResultByJockyByJyo]  WITH NOCHECK ADD  CONSTRAINT [FK_RaceResultByJockyByJyo_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[RaceResultByJockyByJyo] NOCHECK CONSTRAINT [FK_RaceResultByJockyByJyo_Race]


ALTER TABLE [dbo].[RaceResultByJockyByTrackType]  WITH NOCHECK ADD  CONSTRAINT [FK_RaceResultByJockyByTrackType_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[RaceResultByJockyByTrackType] NOCHECK CONSTRAINT [FK_RaceResultByJockyByTrackType_Race]


ALTER TABLE [dbo].[SpecialRace]  WITH NOCHECK ADD  CONSTRAINT [FK_SpecialRace_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[SpecialRace] NOCHECK CONSTRAINT [FK_SpecialRace_Race]


ALTER TABLE [dbo].[SpecialRaceByHorse]  WITH NOCHECK ADD  CONSTRAINT [FK_SpecialRaceByHorse_Race] FOREIGN KEY([RaceID])
REFERENCES [dbo].[Race] ([RaceID])
ALTER TABLE [dbo].[SpecialRaceByHorse] NOCHECK CONSTRAINT [FK_SpecialRaceByHorse_Race]






CREATE UNIQUE NONCLUSTERED INDEX [IX_Race] ON [dbo].[Race]
(
	[RaceDate] DESC,
	[JyoCD] ASC,
	[Kaiji] ASC,
	[Nichiji] ASC,
	[RaceNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_CourseKubunCD] ON [dbo].[Race]
(
	[CourseKubunCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_CourseTypeCD] ON [dbo].[Race]
(
	[CourseTypeCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_DistanceType2CD] ON [dbo].[Race]
(
	[DistanceType2CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_DistanceTypeCD] ON [dbo].[Race]
(
	[DistanceTypeCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_GradeCD] ON [dbo].[Race]
(
	[GradeCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_Include01] ON [dbo].[Race]
(
	[IsNormal] ASC
)
INCLUDE ( 	[RaceDate],
	[RaceID],
	[CourseTypeCD]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_IsNormal] ON [dbo].[Race]
(
	[IsNormal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_JyoCD] ON [dbo].[Race]
(
	[JyoCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_JyokenCD5] ON [dbo].[Race]
(
	[JyokenCD5] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_JyuryoCD] ON [dbo].[Race]
(
	[JyuryoCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_KigoCD] ON [dbo].[Race]
(
	[KigoCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_RaeDate] ON [dbo].[Race]
(
	[RaceDate] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_SmileCD] ON [dbo].[Race]
(
	[SmileCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_SyubetuCD] ON [dbo].[Race]
(
	[SyubetuCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_TenkoCD] ON [dbo].[Race]
(
	[TenkoCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_TrackCD] ON [dbo].[Race]
(
	[TrackCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_TrackConditionCD] ON [dbo].[Race]
(
	[TrackConditionCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_TrackType2CD] ON [dbo].[Race]
(
	[TrackType2CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_TrackType3CD] ON [dbo].[Race]
(
	[TrackType3CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])




CREATE NONCLUSTERED INDEX [IX_Race_TrackTypeCD] ON [dbo].[Race]
(
	[TrackTypeCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])






COMMIT TRANSACTION



