USE [Jackpot]
GO
BEGIN TRANSACTION




ALTER TABLE [dbo].[RaceResultByMyJockyJyokenGrade] DROP CONSTRAINT [PK_RaceResultByMyJockyJyokenGrade01]


ALTER TABLE [dbo].[RaceResultByMyJockyJyokenGrade] ADD  CONSTRAINT [PK_RaceResultByMyJockyJyokenGrade01] PRIMARY KEY NONCLUSTERED 
(
	[RaceID] DESC,
	[KettoNum] ASC,
	[JyokenCD5] ASC,
	[GradeCD] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PS_Date2_636028000248933701] ON [dbo].[RaceResultByMyJockyJyokenGrade]
(
	[RaceDate]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PS_Date2]([RaceDate])


DROP INDEX [ClusteredIndex_on_PS_Date2_636028000248933701] ON [dbo].[RaceResultByMyJockyJyokenGrade]










COMMIT TRANSACTION



