USE [Jackpot]
GO
BEGIN TRANSACTION




ALTER TABLE [dbo].[RaceResultByChildrenJyoken02] DROP CONSTRAINT [PK_RaceResultByChildrenJyoken02]


ALTER TABLE [dbo].[RaceResultByChildrenJyoken02] ADD  CONSTRAINT [PK_RaceResultByChildrenJyoken02] PRIMARY KEY NONCLUSTERED 
(
	[RaceID] DESC,
	[KettoNum] ASC,
	[JyokenCD5] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PS_Date2_636027997044286711] ON [dbo].[RaceResultByChildrenJyoken02]
(
	[RaceDate]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PS_Date2]([RaceDate])


DROP INDEX [ClusteredIndex_on_PS_Date2_636027997044286711] ON [dbo].[RaceResultByChildrenJyoken02]










COMMIT TRANSACTION



