USE [Jackpot]
GO
BEGIN TRANSACTION




ALTER TABLE [dbo].[RaceByLapTime] DROP CONSTRAINT [PK_RaceByLapTime]


ALTER TABLE [dbo].[RaceByLapTime] ADD  CONSTRAINT [PK_RaceByLapTime] PRIMARY KEY NONCLUSTERED 
(
	[RaceID] DESC,
	[ID] ASC
)WITH (PAD_INDEX = ON, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]


CREATE CLUSTERED INDEX [ClusteredIndex_on_PS_Date_636028180627068049] ON [dbo].[RaceByLapTime]
(
	[RaceDate]
)WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PS_Date]([RaceDate])


DROP INDEX [ClusteredIndex_on_PS_Date_636028180627068049] ON [dbo].[RaceByLapTime]








CREATE UNIQUE NONCLUSTERED INDEX [IX_RaceByLapTime] ON [dbo].[RaceByLapTime]
(
	[RaceDate] DESC,
	[JyoCD] ASC,
	[Kaiji] ASC,
	[Nichiji] ASC,
	[RaceNum] ASC,
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = ON, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PS_Date]([RaceDate])






COMMIT TRANSACTION



