USE [Jackpot]
GO
BEGIN TRANSACTION




ALTER TABLE [dbo].[WinFiveByRace] DROP CONSTRAINT [PK_WinFiveByRace]


ALTER TABLE [dbo].[WinFiveByRace] ADD  CONSTRAINT [PK_WinFiveByRace] PRIMARY KEY CLUSTERED 
(
	[KaisaiDate] DESC,
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PS_Date]([KaisaiDate])








COMMIT TRANSACTION



