USE tempdb
GO
DBCC SHRINKFILE(tempdev,8)
DBCC SHRINKFILE(temp2,8)
DBCC SHRINKFILE(temp3,8)
DBCC SHRINKFILE(temp4,8)
DBCC SHRINKFILE(temp5,8)
DBCC SHRINKFILE(temp6,8)
DBCC SHRINKFILE(temp7,8)
DBCC SHRINKFILE(temp8,8)
--DBCC SHRINKFILE(temp9, 8)
DBCC SHRINKFILE(templog,8)