USE master
GO
--ADD
ALTER DATABASE tempdb ADD FILE(NAME = temp11,FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\tempdb_mssql_11.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
ALTER DATABASE tempdb ADD FILE(NAME = temp12,FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\tempdb_mssql_12.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
ALTER DATABASE tempdb ADD FILE(NAME = temp13,FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\tempdb_mssql_13.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
ALTER DATABASE tempdb ADD FILE(NAME = temp14,FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\tempdb_mssql_14.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
ALTER DATABASE tempdb ADD FILE(NAME = temp15,FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\tempdb_mssql_15.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
ALTER DATABASE tempdb ADD FILE(NAME = temp16,FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\tempdb_mssql_16.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
ALTER DATABASE tempdb ADD FILE(NAME = temp17,FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\tempdb_mssql_17.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
ALTER DATABASE tempdb ADD FILE(NAME = temp18,FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\tempdb_mssql_18.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
ALTER DATABASE tempdb ADD FILE(NAME = temp21,FILENAME = N'Y:\Microsoft SQL Server\MSSQL\Data\tempdb_mssql_21.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
ALTER DATABASE tempdb ADD FILE(NAME = temp22,FILENAME = N'Y:\Microsoft SQL Server\MSSQL\Data\tempdb_mssql_22.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
ALTER DATABASE tempdb ADD FILE(NAME = temp23,FILENAME = N'Y:\Microsoft SQL Server\MSSQL\Data\tempdb_mssql_23.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
ALTER DATABASE tempdb ADD FILE(NAME = temp24,FILENAME = N'Y:\Microsoft SQL Server\MSSQL\Data\tempdb_mssql_24.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
ALTER DATABASE tempdb ADD FILE(NAME = temp25,FILENAME = N'Y:\Microsoft SQL Server\MSSQL\Data\tempdb_mssql_25.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
ALTER DATABASE tempdb ADD FILE(NAME = temp26,FILENAME = N'Y:\Microsoft SQL Server\MSSQL\Data\tempdb_mssql_26.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
ALTER DATABASE tempdb ADD FILE(NAME = temp27,FILENAME = N'Y:\Microsoft SQL Server\MSSQL\Data\tempdb_mssql_27.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
ALTER DATABASE tempdb ADD FILE(NAME = temp28,FILENAME = N'Y:\Microsoft SQL Server\MSSQL\Data\tempdb_mssql_28.ndf',SIZE = 10 GB,MAXSIZE = UNLIMITED,FILEGROWTH = 1 GB);
GO