USE master
GO
ALTER DATABASE tempdb
MODIFY FILE
(NAME = temp7, FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\tempdb_mssql_7.ndf', SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB);
GO
ALTER DATABASE tempdb
MODIFY FILE
(NAME = temp8, FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\tempdb_mssql_8.ndf', SIZE = 1GB , MAXSIZE = UNLIMITED, FILEGROWTH = 1GB);
GO
