USE master;
GO
ALTER DATABASE tempdb MODIFY FILE(NAME = temp6, FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\tempdb_mssql_6.ndf', SIZE = 1024 MB, MAXSIZE = UNLIMITED, FILEGROWTH = 1024 MB);
GO
ALTER DATABASE tempdb MODIFY FILE(NAME = temp7, FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\tempdb_mssql_7.ndf', SIZE = 1024 MB, MAXSIZE = UNLIMITED, FILEGROWTH = 1024 MB);
GO